name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]

  workflow_dispatch:

jobs:
  pr-lint:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: PR Lint
        id: pr-lint
        uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true

  run:
    needs: pr-lint
    if: ${{ needs.pr-lint.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "We do not accept PRs. If you have any questions, please feel free to contact us."
