name: PR Lint
permissions: write-all

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]

  workflow_dispatch:

jobs:
  pr-lint:
    name: Validate PR commit title meets commit convention
    runs-on: ubuntu-latest
    steps:
      - name: pr-lint
        uses: amannn/action-semantic-pull-request@v4.5.0
        id: pr-lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true

  close_pull_request:
    runs-on: ubuntu-latest
    needs: your_job_name
    steps:
      - name: Close Pull Request on Failure
        if: ${{ needs.pr-lint.outputs.status == 'failure' }}
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const github = context.github;
            const contextRepo = github.repo;
            const prNumber = context.payload.pull_request.number;

            github.pulls.update({
              owner: contextRepo.owner,
              repo: contextRepo.repo,
              pull_number: prNumber,
              state: 'closed'
            });
          
    
