name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]

  workflow_dispatch:

jobs:
  pr-lint:
    name: Validate PR commit title meets commit convention
    runs-on: ubuntu-latest
    steps:
      - name: PR Lint Step
        id: pr-lint-step
        uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true

  close-pr:
    name: Close PR on failure
    runs-on: ubuntu-latest
    needs: pr-lint
    if: ${{ failure() }}
    steps:
      - name: Close PR
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          PR_NUMBER="${{ github.event.number }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.repository }}"
          
          API_URL="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER"
          
          curl -X PATCH -H "Authorization: token $TOKEN" -H "Content-Type: application/json" \
            -d '{"state":"closed"}' $API_URL
