name: Lint and Close PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions: write-all

jobs:
  code_check:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate PR title
        id: lint_pr_title
        uses: amannn/action-semantic-pull-request@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add linting error comment
        if: steps.lint_pr_title.outputs.error_message != null
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 

            Details:
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
  close-pr:
    name: Process PR
    if: failure()
    needs: code_check
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: get_pr_number
        run: echo "PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Close PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt('${{env.PR_NUMBER}}'),
              state: 'closed'
            })